// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.Service3;

public interface addInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:addInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string naturalResourceId = 1;</code>
   */
  java.lang.String getNaturalResourceId();
  /**
   * <code>string naturalResourceId = 1;</code>
   */
  com.google.protobuf.ByteString
      getNaturalResourceIdBytes();

  /**
   * <code>string wind = 2;</code>
   */
  java.lang.String getWind();
  /**
   * <code>string wind = 2;</code>
   */
  com.google.protobuf.ByteString
      getWindBytes();

  /**
   * <code>string temperature = 3;</code>
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 3;</code>
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();

  /**
   * <code>string typeOfnaturalDisaster = 4;</code>
   */
  java.lang.String getTypeOfnaturalDisaster();
  /**
   * <code>string typeOfnaturalDisaster = 4;</code>
   */
  com.google.protobuf.ByteString
      getTypeOfnaturalDisasterBytes();

  /**
   * <code>string typeOfPollutan = 5;</code>
   */
  java.lang.String getTypeOfPollutan();
  /**
   * <code>string typeOfPollutan = 5;</code>
   */
  com.google.protobuf.ByteString
      getTypeOfPollutanBytes();
}
