// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.Service3;

/**
 * Protobuf type {@code displayLocationDetails}
 */
public  final class displayLocationDetails extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:displayLocationDetails)
    displayLocationDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use displayLocationDetails.newBuilder() to construct.
  private displayLocationDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private displayLocationDetails() {
    cityAdded_ = "";
    cityDetails_ = "";
    locationConfirmation_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private displayLocationDetails(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cityAdded_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cityDetails_ = s;
            break;
          }
          case 24: {

            locationConfirmation_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.Service3.Service3Impl.internal_static_displayLocationDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.Service3.Service3Impl.internal_static_displayLocationDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.Service3.displayLocationDetails.class, ds.Service3.displayLocationDetails.Builder.class);
  }

  public static final int CITYADDED_FIELD_NUMBER = 1;
  private volatile java.lang.Object cityAdded_;
  /**
   * <code>string cityAdded = 1;</code>
   */
  public java.lang.String getCityAdded() {
    java.lang.Object ref = cityAdded_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cityAdded_ = s;
      return s;
    }
  }
  /**
   * <code>string cityAdded = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCityAddedBytes() {
    java.lang.Object ref = cityAdded_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cityAdded_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITYDETAILS_FIELD_NUMBER = 2;
  private volatile java.lang.Object cityDetails_;
  /**
   * <code>string cityDetails = 2;</code>
   */
  public java.lang.String getCityDetails() {
    java.lang.Object ref = cityDetails_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cityDetails_ = s;
      return s;
    }
  }
  /**
   * <code>string cityDetails = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCityDetailsBytes() {
    java.lang.Object ref = cityDetails_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cityDetails_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATIONCONFIRMATION_FIELD_NUMBER = 3;
  private boolean locationConfirmation_;
  /**
   * <code>bool locationConfirmation = 3;</code>
   */
  public boolean getLocationConfirmation() {
    return locationConfirmation_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCityAddedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cityAdded_);
    }
    if (!getCityDetailsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cityDetails_);
    }
    if (locationConfirmation_ != false) {
      output.writeBool(3, locationConfirmation_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCityAddedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cityAdded_);
    }
    if (!getCityDetailsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cityDetails_);
    }
    if (locationConfirmation_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, locationConfirmation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.Service3.displayLocationDetails)) {
      return super.equals(obj);
    }
    ds.Service3.displayLocationDetails other = (ds.Service3.displayLocationDetails) obj;

    boolean result = true;
    result = result && getCityAdded()
        .equals(other.getCityAdded());
    result = result && getCityDetails()
        .equals(other.getCityDetails());
    result = result && (getLocationConfirmation()
        == other.getLocationConfirmation());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CITYADDED_FIELD_NUMBER;
    hash = (53 * hash) + getCityAdded().hashCode();
    hash = (37 * hash) + CITYDETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getCityDetails().hashCode();
    hash = (37 * hash) + LOCATIONCONFIRMATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLocationConfirmation());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.Service3.displayLocationDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service3.displayLocationDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service3.displayLocationDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service3.displayLocationDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service3.displayLocationDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service3.displayLocationDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service3.displayLocationDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.Service3.displayLocationDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.Service3.displayLocationDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.Service3.displayLocationDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.Service3.displayLocationDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.Service3.displayLocationDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.Service3.displayLocationDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code displayLocationDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:displayLocationDetails)
      ds.Service3.displayLocationDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.Service3.Service3Impl.internal_static_displayLocationDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.Service3.Service3Impl.internal_static_displayLocationDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.Service3.displayLocationDetails.class, ds.Service3.displayLocationDetails.Builder.class);
    }

    // Construct using ds.Service3.displayLocationDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cityAdded_ = "";

      cityDetails_ = "";

      locationConfirmation_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.Service3.Service3Impl.internal_static_displayLocationDetails_descriptor;
    }

    @java.lang.Override
    public ds.Service3.displayLocationDetails getDefaultInstanceForType() {
      return ds.Service3.displayLocationDetails.getDefaultInstance();
    }

    @java.lang.Override
    public ds.Service3.displayLocationDetails build() {
      ds.Service3.displayLocationDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.Service3.displayLocationDetails buildPartial() {
      ds.Service3.displayLocationDetails result = new ds.Service3.displayLocationDetails(this);
      result.cityAdded_ = cityAdded_;
      result.cityDetails_ = cityDetails_;
      result.locationConfirmation_ = locationConfirmation_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.Service3.displayLocationDetails) {
        return mergeFrom((ds.Service3.displayLocationDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.Service3.displayLocationDetails other) {
      if (other == ds.Service3.displayLocationDetails.getDefaultInstance()) return this;
      if (!other.getCityAdded().isEmpty()) {
        cityAdded_ = other.cityAdded_;
        onChanged();
      }
      if (!other.getCityDetails().isEmpty()) {
        cityDetails_ = other.cityDetails_;
        onChanged();
      }
      if (other.getLocationConfirmation() != false) {
        setLocationConfirmation(other.getLocationConfirmation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.Service3.displayLocationDetails parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.Service3.displayLocationDetails) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object cityAdded_ = "";
    /**
     * <code>string cityAdded = 1;</code>
     */
    public java.lang.String getCityAdded() {
      java.lang.Object ref = cityAdded_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cityAdded_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cityAdded = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCityAddedBytes() {
      java.lang.Object ref = cityAdded_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cityAdded_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cityAdded = 1;</code>
     */
    public Builder setCityAdded(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cityAdded_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cityAdded = 1;</code>
     */
    public Builder clearCityAdded() {
      
      cityAdded_ = getDefaultInstance().getCityAdded();
      onChanged();
      return this;
    }
    /**
     * <code>string cityAdded = 1;</code>
     */
    public Builder setCityAddedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cityAdded_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cityDetails_ = "";
    /**
     * <code>string cityDetails = 2;</code>
     */
    public java.lang.String getCityDetails() {
      java.lang.Object ref = cityDetails_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cityDetails_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cityDetails = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCityDetailsBytes() {
      java.lang.Object ref = cityDetails_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cityDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cityDetails = 2;</code>
     */
    public Builder setCityDetails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cityDetails_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cityDetails = 2;</code>
     */
    public Builder clearCityDetails() {
      
      cityDetails_ = getDefaultInstance().getCityDetails();
      onChanged();
      return this;
    }
    /**
     * <code>string cityDetails = 2;</code>
     */
    public Builder setCityDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cityDetails_ = value;
      onChanged();
      return this;
    }

    private boolean locationConfirmation_ ;
    /**
     * <code>bool locationConfirmation = 3;</code>
     */
    public boolean getLocationConfirmation() {
      return locationConfirmation_;
    }
    /**
     * <code>bool locationConfirmation = 3;</code>
     */
    public Builder setLocationConfirmation(boolean value) {
      
      locationConfirmation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool locationConfirmation = 3;</code>
     */
    public Builder clearLocationConfirmation() {
      
      locationConfirmation_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

	public void setLocationConfirmationt(boolean b) {
		// TODO Auto-generated method stub
		
	}


    // @@protoc_insertion_point(builder_scope:displayLocationDetails)
  }

  // @@protoc_insertion_point(class_scope:displayLocationDetails)
  private static final ds.Service3.displayLocationDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.Service3.displayLocationDetails();
  }

  public static ds.Service3.displayLocationDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<displayLocationDetails>
      PARSER = new com.google.protobuf.AbstractParser<displayLocationDetails>() {
    @java.lang.Override
    public displayLocationDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new displayLocationDetails(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<displayLocationDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<displayLocationDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.Service3.displayLocationDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

