// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.Service3;

public interface enterCityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:enterCity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cityAdded = 1;</code>
   */
  java.lang.String getCityAdded();
  /**
   * <code>string cityAdded = 1;</code>
   */
  com.google.protobuf.ByteString
      getCityAddedBytes();
}
