// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.Service3;

public interface responseDataRecordedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:responseDataRecorded)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string displayDataRecorded = 1;</code>
   */
  java.lang.String getDisplayDataRecorded();
  /**
   * <code>string displayDataRecorded = 1;</code>
   */
  com.google.protobuf.ByteString
      getDisplayDataRecordedBytes();

  /**
   * <code>string confirmingCityDetails = 2;</code>
   */
  java.lang.String getConfirmingCityDetails();
  /**
   * <code>string confirmingCityDetails = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfirmingCityDetailsBytes();

  /**
   * <code>string naturalResourceLastAdded = 3;</code>
   */
  java.lang.String getNaturalResourceLastAdded();
  /**
   * <code>string naturalResourceLastAdded = 3;</code>
   */
  com.google.protobuf.ByteString
      getNaturalResourceLastAddedBytes();
}
