// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.Service3;

public interface responseAddInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:responseAddInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resourcesMessageConfirmation = 1;</code>
   */
  java.lang.String getResourcesMessageConfirmation();
  /**
   * <code>string resourcesMessageConfirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getResourcesMessageConfirmationBytes();

  /**
   * <code>string lastAddedMsg = 2;</code>
   */
  java.lang.String getLastAddedMsg();
  /**
   * <code>string lastAddedMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastAddedMsgBytes();

  /**
   * <code>string naturalResourceLastAdded = 3;</code>
   */
  java.lang.String getNaturalResourceLastAdded();
  /**
   * <code>string naturalResourceLastAdded = 3;</code>
   */
  com.google.protobuf.ByteString
      getNaturalResourceLastAddedBytes();
}
