// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.Service3;

/**
 * Protobuf type {@code responseDataRecorded}
 */
public  final class responseDataRecorded extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:responseDataRecorded)
    responseDataRecordedOrBuilder {
private static final long serialVersionUID = 0L;
  // Use responseDataRecorded.newBuilder() to construct.
  private responseDataRecorded(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private responseDataRecorded() {
    displayDataRecorded_ = "";
    confirmingCityDetails_ = "";
    naturalResourceLastAdded_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private responseDataRecorded(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            displayDataRecorded_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            confirmingCityDetails_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            naturalResourceLastAdded_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.Service3.Service3Impl.internal_static_responseDataRecorded_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.Service3.Service3Impl.internal_static_responseDataRecorded_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.Service3.responseDataRecorded.class, ds.Service3.responseDataRecorded.Builder.class);
  }

  public static final int DISPLAYDATARECORDED_FIELD_NUMBER = 1;
  private volatile java.lang.Object displayDataRecorded_;
  /**
   * <code>string displayDataRecorded = 1;</code>
   */
  public java.lang.String getDisplayDataRecorded() {
    java.lang.Object ref = displayDataRecorded_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayDataRecorded_ = s;
      return s;
    }
  }
  /**
   * <code>string displayDataRecorded = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayDataRecordedBytes() {
    java.lang.Object ref = displayDataRecorded_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayDataRecorded_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIRMINGCITYDETAILS_FIELD_NUMBER = 2;
  private volatile java.lang.Object confirmingCityDetails_;
  /**
   * <code>string confirmingCityDetails = 2;</code>
   */
  public java.lang.String getConfirmingCityDetails() {
    java.lang.Object ref = confirmingCityDetails_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      confirmingCityDetails_ = s;
      return s;
    }
  }
  /**
   * <code>string confirmingCityDetails = 2;</code>
   */
  public com.google.protobuf.ByteString
      getConfirmingCityDetailsBytes() {
    java.lang.Object ref = confirmingCityDetails_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      confirmingCityDetails_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NATURALRESOURCELASTADDED_FIELD_NUMBER = 3;
  private volatile java.lang.Object naturalResourceLastAdded_;
  /**
   * <code>string naturalResourceLastAdded = 3;</code>
   */
  public java.lang.String getNaturalResourceLastAdded() {
    java.lang.Object ref = naturalResourceLastAdded_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      naturalResourceLastAdded_ = s;
      return s;
    }
  }
  /**
   * <code>string naturalResourceLastAdded = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNaturalResourceLastAddedBytes() {
    java.lang.Object ref = naturalResourceLastAdded_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      naturalResourceLastAdded_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDisplayDataRecordedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, displayDataRecorded_);
    }
    if (!getConfirmingCityDetailsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, confirmingCityDetails_);
    }
    if (!getNaturalResourceLastAddedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, naturalResourceLastAdded_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDisplayDataRecordedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, displayDataRecorded_);
    }
    if (!getConfirmingCityDetailsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, confirmingCityDetails_);
    }
    if (!getNaturalResourceLastAddedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, naturalResourceLastAdded_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.Service3.responseDataRecorded)) {
      return super.equals(obj);
    }
    ds.Service3.responseDataRecorded other = (ds.Service3.responseDataRecorded) obj;

    boolean result = true;
    result = result && getDisplayDataRecorded()
        .equals(other.getDisplayDataRecorded());
    result = result && getConfirmingCityDetails()
        .equals(other.getConfirmingCityDetails());
    result = result && getNaturalResourceLastAdded()
        .equals(other.getNaturalResourceLastAdded());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISPLAYDATARECORDED_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayDataRecorded().hashCode();
    hash = (37 * hash) + CONFIRMINGCITYDETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getConfirmingCityDetails().hashCode();
    hash = (37 * hash) + NATURALRESOURCELASTADDED_FIELD_NUMBER;
    hash = (53 * hash) + getNaturalResourceLastAdded().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.Service3.responseDataRecorded parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service3.responseDataRecorded parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service3.responseDataRecorded parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service3.responseDataRecorded parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service3.responseDataRecorded parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service3.responseDataRecorded parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service3.responseDataRecorded parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.Service3.responseDataRecorded parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.Service3.responseDataRecorded parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.Service3.responseDataRecorded parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.Service3.responseDataRecorded parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.Service3.responseDataRecorded parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.Service3.responseDataRecorded prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code responseDataRecorded}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:responseDataRecorded)
      ds.Service3.responseDataRecordedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.Service3.Service3Impl.internal_static_responseDataRecorded_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.Service3.Service3Impl.internal_static_responseDataRecorded_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.Service3.responseDataRecorded.class, ds.Service3.responseDataRecorded.Builder.class);
    }

    // Construct using ds.Service3.responseDataRecorded.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      displayDataRecorded_ = "";

      confirmingCityDetails_ = "";

      naturalResourceLastAdded_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.Service3.Service3Impl.internal_static_responseDataRecorded_descriptor;
    }

    @java.lang.Override
    public ds.Service3.responseDataRecorded getDefaultInstanceForType() {
      return ds.Service3.responseDataRecorded.getDefaultInstance();
    }

    @java.lang.Override
    public ds.Service3.responseDataRecorded build() {
      ds.Service3.responseDataRecorded result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.Service3.responseDataRecorded buildPartial() {
      ds.Service3.responseDataRecorded result = new ds.Service3.responseDataRecorded(this);
      result.displayDataRecorded_ = displayDataRecorded_;
      result.confirmingCityDetails_ = confirmingCityDetails_;
      result.naturalResourceLastAdded_ = naturalResourceLastAdded_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.Service3.responseDataRecorded) {
        return mergeFrom((ds.Service3.responseDataRecorded)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.Service3.responseDataRecorded other) {
      if (other == ds.Service3.responseDataRecorded.getDefaultInstance()) return this;
      if (!other.getDisplayDataRecorded().isEmpty()) {
        displayDataRecorded_ = other.displayDataRecorded_;
        onChanged();
      }
      if (!other.getConfirmingCityDetails().isEmpty()) {
        confirmingCityDetails_ = other.confirmingCityDetails_;
        onChanged();
      }
      if (!other.getNaturalResourceLastAdded().isEmpty()) {
        naturalResourceLastAdded_ = other.naturalResourceLastAdded_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.Service3.responseDataRecorded parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.Service3.responseDataRecorded) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object displayDataRecorded_ = "";
    /**
     * <code>string displayDataRecorded = 1;</code>
     */
    public java.lang.String getDisplayDataRecorded() {
      java.lang.Object ref = displayDataRecorded_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayDataRecorded_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayDataRecorded = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayDataRecordedBytes() {
      java.lang.Object ref = displayDataRecorded_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayDataRecorded_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayDataRecorded = 1;</code>
     */
    public Builder setDisplayDataRecorded(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayDataRecorded_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayDataRecorded = 1;</code>
     */
    public Builder clearDisplayDataRecorded() {
      
      displayDataRecorded_ = getDefaultInstance().getDisplayDataRecorded();
      onChanged();
      return this;
    }
    /**
     * <code>string displayDataRecorded = 1;</code>
     */
    public Builder setDisplayDataRecordedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayDataRecorded_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object confirmingCityDetails_ = "";
    /**
     * <code>string confirmingCityDetails = 2;</code>
     */
    public java.lang.String getConfirmingCityDetails() {
      java.lang.Object ref = confirmingCityDetails_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        confirmingCityDetails_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string confirmingCityDetails = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConfirmingCityDetailsBytes() {
      java.lang.Object ref = confirmingCityDetails_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        confirmingCityDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string confirmingCityDetails = 2;</code>
     */
    public Builder setConfirmingCityDetails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      confirmingCityDetails_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string confirmingCityDetails = 2;</code>
     */
    public Builder clearConfirmingCityDetails() {
      
      confirmingCityDetails_ = getDefaultInstance().getConfirmingCityDetails();
      onChanged();
      return this;
    }
    /**
     * <code>string confirmingCityDetails = 2;</code>
     */
    public Builder setConfirmingCityDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      confirmingCityDetails_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object naturalResourceLastAdded_ = "";
    /**
     * <code>string naturalResourceLastAdded = 3;</code>
     */
    public java.lang.String getNaturalResourceLastAdded() {
      java.lang.Object ref = naturalResourceLastAdded_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        naturalResourceLastAdded_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string naturalResourceLastAdded = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNaturalResourceLastAddedBytes() {
      java.lang.Object ref = naturalResourceLastAdded_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        naturalResourceLastAdded_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string naturalResourceLastAdded = 3;</code>
     */
    public Builder setNaturalResourceLastAdded(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      naturalResourceLastAdded_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string naturalResourceLastAdded = 3;</code>
     */
    public Builder clearNaturalResourceLastAdded() {
      
      naturalResourceLastAdded_ = getDefaultInstance().getNaturalResourceLastAdded();
      onChanged();
      return this;
    }
    /**
     * <code>string naturalResourceLastAdded = 3;</code>
     */
    public Builder setNaturalResourceLastAddedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      naturalResourceLastAdded_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:responseDataRecorded)
  }

  // @@protoc_insertion_point(class_scope:responseDataRecorded)
  private static final ds.Service3.responseDataRecorded DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.Service3.responseDataRecorded();
  }

  public static ds.Service3.responseDataRecorded getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<responseDataRecorded>
      PARSER = new com.google.protobuf.AbstractParser<responseDataRecorded>() {
    @java.lang.Override
    public responseDataRecorded parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new responseDataRecorded(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<responseDataRecorded> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<responseDataRecorded> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.Service3.responseDataRecorded getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

