// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.Service3;

public interface selectViewInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:selectViewInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string viewInfoRegistered = 1;</code>
   */
  java.lang.String getViewInfoRegistered();
  /**
   * <code>string viewInfoRegistered = 1;</code>
   */
  com.google.protobuf.ByteString
      getViewInfoRegisteredBytes();
}
