// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.Service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_enterCity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_enterCity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_displayLocationDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_displayLocationDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_addInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_addInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_responseAddInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_responseAddInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_selectViewInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_selectViewInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_responseDataRecorded_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_responseDataRecorded_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\"\036\n\tenterCity\022\021\n\tcityAdd" +
      "ed\030\001 \001(\t\"^\n\026displayLocationDetails\022\021\n\tci" +
      "tyAdded\030\001 \001(\t\022\023\n\013cityDetails\030\002 \001(\t\022\034\n\024lo" +
      "cationConfirmation\030\003 \001(\010\"~\n\007addInfo\022\031\n\021n" +
      "aturalResourceId\030\001 \001(\t\022\014\n\004wind\030\002 \001(\t\022\023\n\013" +
      "temperature\030\003 \001(\t\022\035\n\025typeOfnaturalDisast" +
      "er\030\004 \001(\t\022\026\n\016typeOfPollutan\030\005 \001(\t\"o\n\017resp" +
      "onseAddInfo\022$\n\034resourcesMessageConfirmat" +
      "ion\030\001 \001(\t\022\024\n\014lastAddedMsg\030\002 \001(\t\022 \n\030natur" +
      "alResourceLastAdded\030\003 \001(\t\",\n\016selectViewI" +
      "nfo\022\032\n\022viewInfoRegistered\030\001 \001(\t\"j\n\024respo" +
      "nseDataRecorded\022\033\n\023displayDataRecorded\030\001" +
      " \001(\t\022\023\n\013cityDetails\030\002 \001(\t\022 \n\030naturalReso" +
      "urceLastAdded\030\003 \001(\t2\266\001\n\010service3\0228\n\rente" +
      "rLocation\022\n.enterCity\032\027.displayLocationD" +
      "etails\"\0000\001\0221\n\raddingDetails\022\010.addInfo\032\020." +
      "responseAddInfo\"\000(\0010\001\022=\n\017displayRecorded" +
      "\022\017.selectViewInfo\032\025.responseDataRecorded" +
      "\"\0000\001B\035\n\013ds.Service3B\014Service3ImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_enterCity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_enterCity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_enterCity_descriptor,
        new java.lang.String[] { "CityAdded", });
    internal_static_displayLocationDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_displayLocationDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_displayLocationDetails_descriptor,
        new java.lang.String[] { "CityAdded", "CityDetails", "LocationConfirmation", });
    internal_static_addInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_addInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_addInfo_descriptor,
        new java.lang.String[] { "NaturalResourceId", "Wind", "Temperature", "TypeOfnaturalDisaster", "TypeOfPollutan", });
    internal_static_responseAddInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_responseAddInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_responseAddInfo_descriptor,
        new java.lang.String[] { "ResourcesMessageConfirmation", "LastAddedMsg", "NaturalResourceLastAdded", });
    internal_static_selectViewInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_selectViewInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_selectViewInfo_descriptor,
        new java.lang.String[] { "ViewInfoRegistered", });
    internal_static_responseDataRecorded_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_responseDataRecorded_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_responseDataRecorded_descriptor,
        new java.lang.String[] { "DisplayDataRecorded", "CityDetails", "NaturalResourceLastAdded", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
