// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByLocation.proto

package ds.SearchingByLocation;

public interface scanCityEnteredOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scanCityEntered)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataCityInfo = 3;</code>
   */
  java.lang.String getDataCityInfo();
  /**
   * <code>string dataCityInfo = 3;</code>
   */
  com.google.protobuf.ByteString
      getDataCityInfoBytes();
}
