// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByLocation.proto

package ds.SearchingByLocation;

public interface verifyStationRequestedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:verifyStationRequested)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataCityInfo = 3;</code>
   */
  java.lang.String getDataCityInfo();
  /**
   * <code>string dataCityInfo = 3;</code>
   */
  com.google.protobuf.ByteString
      getDataCityInfoBytes();

  /**
   * <code>bool checkingStation = 1;</code>
   */
  boolean getCheckingStation();

  /**
   * <code>string stationFound = 4;</code>
   */
  java.lang.String getStationFound();
  /**
   * <code>string stationFound = 4;</code>
   */
  com.google.protobuf.ByteString
      getStationFoundBytes();
}
