// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByLocation.proto

package ds.SearchingByLocation;

public interface waterAirQualityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterAirQuality)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataCityInfo = 3;</code>
   */
  java.lang.String getDataCityInfo();
  /**
   * <code>string dataCityInfo = 3;</code>
   */
  com.google.protobuf.ByteString
      getDataCityInfoBytes();

  /**
   * <code>string stationFound = 4;</code>
   */
  java.lang.String getStationFound();
  /**
   * <code>string stationFound = 4;</code>
   */
  com.google.protobuf.ByteString
      getStationFoundBytes();

  /**
   * <code>string reportAirQuality = 5;</code>
   */
  java.lang.String getReportAirQuality();
  /**
   * <code>string reportAirQuality = 5;</code>
   */
  com.google.protobuf.ByteString
      getReportAirQualityBytes();
}
