// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByPeriod.proto

package ds.SearchingByPeriod;

/**
 * Protobuf type {@code identifyPeriod}
 */
public  final class identifyPeriod extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:identifyPeriod)
    identifyPeriodOrBuilder {
private static final long serialVersionUID = 0L;
  // Use identifyPeriod.newBuilder() to construct.
  private identifyPeriod(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private identifyPeriod() {
    consultingPeriod_ = "";
    periodIdentification_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private identifyPeriod(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            periodIdentification_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            consultingPeriod_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.SearchingByPeriod.searchingByPeriodImpl.internal_static_identifyPeriod_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.SearchingByPeriod.searchingByPeriodImpl.internal_static_identifyPeriod_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.SearchingByPeriod.identifyPeriod.class, ds.SearchingByPeriod.identifyPeriod.Builder.class);
  }

  public static final int CONSULTINGPERIOD_FIELD_NUMBER = 2;
  private volatile java.lang.Object consultingPeriod_;
  /**
   * <pre>
   *it is the type that are in our message and has to convert the message into a series of bites
   * </pre>
   *
   * <code>string consultingPeriod = 2;</code>
   */
  public java.lang.String getConsultingPeriod() {
    java.lang.Object ref = consultingPeriod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      consultingPeriod_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *it is the type that are in our message and has to convert the message into a series of bites
   * </pre>
   *
   * <code>string consultingPeriod = 2;</code>
   */
  public com.google.protobuf.ByteString
      getConsultingPeriodBytes() {
    java.lang.Object ref = consultingPeriod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      consultingPeriod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERIODIDENTIFICATION_FIELD_NUMBER = 1;
  private boolean periodIdentification_;
  /**
   * <code>bool periodIdentification = 1;</code>
   */
  public boolean getPeriodIdentification() {
    return periodIdentification_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (periodIdentification_ != false) {
      output.writeBool(1, periodIdentification_);
    }
    if (!getConsultingPeriodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, consultingPeriod_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (periodIdentification_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, periodIdentification_);
    }
    if (!getConsultingPeriodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, consultingPeriod_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.SearchingByPeriod.identifyPeriod)) {
      return super.equals(obj);
    }
    ds.SearchingByPeriod.identifyPeriod other = (ds.SearchingByPeriod.identifyPeriod) obj;

    boolean result = true;
    result = result && getConsultingPeriod()
        .equals(other.getConsultingPeriod());
    result = result && (getPeriodIdentification()
        == other.getPeriodIdentification());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONSULTINGPERIOD_FIELD_NUMBER;
    hash = (53 * hash) + getConsultingPeriod().hashCode();
    hash = (37 * hash) + PERIODIDENTIFICATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPeriodIdentification());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.SearchingByPeriod.identifyPeriod parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.SearchingByPeriod.identifyPeriod parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.SearchingByPeriod.identifyPeriod parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.SearchingByPeriod.identifyPeriod parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.SearchingByPeriod.identifyPeriod parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.SearchingByPeriod.identifyPeriod parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.SearchingByPeriod.identifyPeriod parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.SearchingByPeriod.identifyPeriod parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.SearchingByPeriod.identifyPeriod parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.SearchingByPeriod.identifyPeriod parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.SearchingByPeriod.identifyPeriod parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.SearchingByPeriod.identifyPeriod parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.SearchingByPeriod.identifyPeriod prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code identifyPeriod}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:identifyPeriod)
      ds.SearchingByPeriod.identifyPeriodOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.SearchingByPeriod.searchingByPeriodImpl.internal_static_identifyPeriod_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.SearchingByPeriod.searchingByPeriodImpl.internal_static_identifyPeriod_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.SearchingByPeriod.identifyPeriod.class, ds.SearchingByPeriod.identifyPeriod.Builder.class);
    }

    // Construct using ds.SearchingByPeriod.identifyPeriod.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      consultingPeriod_ = "";

      periodIdentification_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.SearchingByPeriod.searchingByPeriodImpl.internal_static_identifyPeriod_descriptor;
    }

    @java.lang.Override
    public ds.SearchingByPeriod.identifyPeriod getDefaultInstanceForType() {
      return ds.SearchingByPeriod.identifyPeriod.getDefaultInstance();
    }

    @java.lang.Override
    public ds.SearchingByPeriod.identifyPeriod build() {
      ds.SearchingByPeriod.identifyPeriod result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.SearchingByPeriod.identifyPeriod buildPartial() {
      ds.SearchingByPeriod.identifyPeriod result = new ds.SearchingByPeriod.identifyPeriod(this);
      result.consultingPeriod_ = consultingPeriod_;
      result.periodIdentification_ = periodIdentification_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.SearchingByPeriod.identifyPeriod) {
        return mergeFrom((ds.SearchingByPeriod.identifyPeriod)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.SearchingByPeriod.identifyPeriod other) {
      if (other == ds.SearchingByPeriod.identifyPeriod.getDefaultInstance()) return this;
      if (!other.getConsultingPeriod().isEmpty()) {
        consultingPeriod_ = other.consultingPeriod_;
        onChanged();
      }
      if (other.getPeriodIdentification() != false) {
        setPeriodIdentification(other.getPeriodIdentification());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.SearchingByPeriod.identifyPeriod parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.SearchingByPeriod.identifyPeriod) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object consultingPeriod_ = "";
    /**
     * <pre>
     *it is the type that are in our message and has to convert the message into a series of bites
     * </pre>
     *
     * <code>string consultingPeriod = 2;</code>
     */
    public java.lang.String getConsultingPeriod() {
      java.lang.Object ref = consultingPeriod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consultingPeriod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *it is the type that are in our message and has to convert the message into a series of bites
     * </pre>
     *
     * <code>string consultingPeriod = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConsultingPeriodBytes() {
      java.lang.Object ref = consultingPeriod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consultingPeriod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *it is the type that are in our message and has to convert the message into a series of bites
     * </pre>
     *
     * <code>string consultingPeriod = 2;</code>
     */
    public Builder setConsultingPeriod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      consultingPeriod_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *it is the type that are in our message and has to convert the message into a series of bites
     * </pre>
     *
     * <code>string consultingPeriod = 2;</code>
     */
    public Builder clearConsultingPeriod() {
      
      consultingPeriod_ = getDefaultInstance().getConsultingPeriod();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *it is the type that are in our message and has to convert the message into a series of bites
     * </pre>
     *
     * <code>string consultingPeriod = 2;</code>
     */
    public Builder setConsultingPeriodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      consultingPeriod_ = value;
      onChanged();
      return this;
    }

    private boolean periodIdentification_ ;
    /**
     * <code>bool periodIdentification = 1;</code>
     */
    public boolean getPeriodIdentification() {
      return periodIdentification_;
    }
    /**
     * <code>bool periodIdentification = 1;</code>
     */
    public Builder setPeriodIdentification(boolean value) {
      
      periodIdentification_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool periodIdentification = 1;</code>
     */
    public Builder clearPeriodIdentification() {
      
      periodIdentification_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:identifyPeriod)
  }

  // @@protoc_insertion_point(class_scope:identifyPeriod)
  private static final ds.SearchingByPeriod.identifyPeriod DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.SearchingByPeriod.identifyPeriod();
  }

  public static ds.SearchingByPeriod.identifyPeriod getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<identifyPeriod>
      PARSER = new com.google.protobuf.AbstractParser<identifyPeriod>() {
    @java.lang.Override
    public identifyPeriod parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new identifyPeriod(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<identifyPeriod> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<identifyPeriod> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.SearchingByPeriod.identifyPeriod getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

