// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByPeriod.proto

package ds.SearchingByPeriod;

public interface reportAirWaterQualityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reportAirWaterQuality)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consultingPeriod = 2;</code>
   */
  java.lang.String getConsultingPeriod();
  /**
   * <code>string consultingPeriod = 2;</code>
   */
  com.google.protobuf.ByteString
      getConsultingPeriodBytes();

  /**
   * <code>string myResourseType = 1;</code>
   */
  java.lang.String getMyResourseType();
  /**
   * <code>string myResourseType = 1;</code>
   */
  com.google.protobuf.ByteString
      getMyResourseTypeBytes();

  /**
   * <code>string qualityReport = 3;</code>
   */
  java.lang.String getQualityReport();
  /**
   * <code>string qualityReport = 3;</code>
   */
  com.google.protobuf.ByteString
      getQualityReportBytes();
}
