// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByPeriod.proto

package ds.SearchingByPeriod;

public interface resourseTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resourseType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string myResourseType = 1;</code>
   */
  java.lang.String getMyResourseType();
  /**
   * <code>string myResourseType = 1;</code>
   */
  com.google.protobuf.ByteString
      getMyResourseTypeBytes();
}
