// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userCollaboration.proto

package grpc.newServices;

public interface addInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:addInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string naturalResourceInfo = 4;</code>
   */
  java.lang.String getNaturalResourceInfo();
  /**
   * <code>string naturalResourceInfo = 4;</code>
   */
  com.google.protobuf.ByteString
      getNaturalResourceInfoBytes();
}
