// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userCollaboration.proto

package grpc.newServices;

public interface displayLocationDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:displayLocationDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cityAdded = 3;</code>
   */
  java.lang.String getCityAdded();
  /**
   * <code>string cityAdded = 3;</code>
   */
  com.google.protobuf.ByteString
      getCityAddedBytes();

  /**
   * <code>string confirmingCityDetails = 2;</code>
   */
  java.lang.String getConfirmingCityDetails();
  /**
   * <code>string confirmingCityDetails = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfirmingCityDetailsBytes();

  /**
   * <code>bool locationConfirmation = 1;</code>
   */
  boolean getLocationConfirmation();
}
