// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByLocation.proto

package grpc.newServices;

public interface enterLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:enterLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cityInput = 1;</code>
   */
  java.lang.String getCityInput();
  /**
   * <code>string cityInput = 1;</code>
   */
  com.google.protobuf.ByteString
      getCityInputBytes();
}
