// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userCollaboration.proto

package grpc.newServices;

public interface enterCityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:enterCity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cityAdded = 3;</code>
   */
  java.lang.String getCityAdded();
  /**
   * <code>string cityAdded = 3;</code>
   */
  com.google.protobuf.ByteString
      getCityAddedBytes();
}
