// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByPeriod.proto

package grpc.newServices;

public interface identifyPeriodOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identifyPeriod)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *it is the type that are in our message and has to convert the message into a series of bites
   * </pre>
   *
   * <code>string consultingPeriod = 2;</code>
   */
  java.lang.String getConsultingPeriod();
  /**
   * <pre>
   *it is the type that are in our message and has to convert the message into a series of bites
   * </pre>
   *
   * <code>string consultingPeriod = 2;</code>
   */
  com.google.protobuf.ByteString
      getConsultingPeriodBytes();

  /**
   * <code>bool periodIdentification = 1;</code>
   */
  boolean getPeriodIdentification();
}
