// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByPeriod.proto

package grpc.newServices;

public interface periodRequestedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:periodRequested)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consultingPeriod = 2;</code>
   */
  java.lang.String getConsultingPeriod();
  /**
   * <code>string consultingPeriod = 2;</code>
   */
  com.google.protobuf.ByteString
      getConsultingPeriodBytes();
}
