// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByPeriod.proto

package grpc.newServices;

public interface registrationTypeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registrationTypeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string naturalResourceRegistered = 2;</code>
   */
  java.lang.String getNaturalResourceRegistered();
  /**
   * <code>string naturalResourceRegistered = 2;</code>
   */
  com.google.protobuf.ByteString
      getNaturalResourceRegisteredBytes();
}
