// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByLocation.proto

package grpc.newServices;

public final class searchingByLocationImpl {
  private searchingByLocationImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_enterLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_enterLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_displayCityInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_displayCityInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scanCityEntered_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scanCityEntered_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_verifyStationRequested_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_verifyStationRequested_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterAirQuality_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterAirQuality_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031searchingByLocation.proto\"\"\n\renterLoca" +
      "tion\022\021\n\tcityInput\030\001 \001(\t\"U\n\017displayCityIn" +
      "fo\022\024\n\014dataCityInfo\030\003 \001(\t\022\026\n\016emptyCityInp" +
      "ut\030\001 \001(\010\022\024\n\014errorMessage\030\002 \001(\t\"\'\n\017scanCi" +
      "tyEntered\022\024\n\014dataCityInfo\030\003 \001(\t\"]\n\026verif" +
      "yStationRequested\022\024\n\014dataCityInfo\030\003 \001(\t\022" +
      "\027\n\017checkingStation\030\001 \001(\010\022\024\n\014stationFound" +
      "\030\004 \001(\t\"W\n\017waterAirQuality\022\024\n\014dataCityInf" +
      "o\030\002 \001(\t\022\024\n\014stationFound\030\004 \001(\t\022\030\n\020reportA" +
      "irQuality\030\005 \001(\t2\342\001\n\023searchingByLocation\022" +
      "7\n\017displayLocation\022\016.enterLocation\032\020.dis" +
      "playCityInfo\"\000(\001\022M\n\032checkingMonitoringSt" +
      "ations\022\020.scanCityEntered\032\027.verifyStation" +
      "Requested\"\000(\0010\001\022C\n\022airQualityResponse\022\027." +
      "verifyStationRequested\032\020.waterAirQuality" +
      "\"\0000\001B-\n\020grpc.newServicesB\027searchingByLoc" +
      "ationImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_enterLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_enterLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_enterLocation_descriptor,
        new java.lang.String[] { "CityInput", });
    internal_static_displayCityInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_displayCityInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_displayCityInfo_descriptor,
        new java.lang.String[] { "DataCityInfo", "EmptyCityInput", "ErrorMessage", });
    internal_static_scanCityEntered_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_scanCityEntered_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scanCityEntered_descriptor,
        new java.lang.String[] { "DataCityInfo", });
    internal_static_verifyStationRequested_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_verifyStationRequested_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_verifyStationRequested_descriptor,
        new java.lang.String[] { "DataCityInfo", "CheckingStation", "StationFound", });
    internal_static_waterAirQuality_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_waterAirQuality_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterAirQuality_descriptor,
        new java.lang.String[] { "DataCityInfo", "StationFound", "ReportAirQuality", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
