// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchingByPeriod.proto

package grpc.newServices;

public final class searchingByPeriodImpl {
  private searchingByPeriodImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_periodRequested_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_periodRequested_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identifyPeriod_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identifyPeriod_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resourseType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resourseType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registrationTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registrationTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reportAirWaterQuality_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reportAirWaterQuality_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027searchingByPeriod.proto\"+\n\017periodReque" +
      "sted\022\030\n\020consultingPeriod\030\002 \001(\t\"H\n\016identi" +
      "fyPeriod\022\030\n\020consultingPeriod\030\002 \001(\t\022\034\n\024pe" +
      "riodIdentification\030\001 \001(\010\"&\n\014resourseType" +
      "\022\026\n\016myResourseType\030\001 \001(\t\"=\n\030registration" +
      "TypeResponse\022!\n\031naturalResourceRegistere" +
      "d\030\002 \001(\t\"`\n\025reportAirWaterQuality\022\030\n\020cons" +
      "ultingPeriod\030\002 \001(\t\022\026\n\016myResourseType\030\001 \001" +
      "(\t\022\025\n\rqualityReport\030\003 \001(\t2\334\001\n\021searchingB" +
      "yPeriod\0226\n\rrequestPeriod\022\020.periodRequest" +
      "ed\032\017.identifyPeriod\"\000(\001\022F\n\030enterNaturalR" +
      "esourcetype\022\r.resourseType\032\031.registratio" +
      "nTypeResponse\"\000\022G\n\030returnAirQualitybyPer" +
      "iod\022\017.identifyPeriod\032\026.reportAirWaterQua" +
      "lity\"\0000\001B+\n\020grpc.newServicesB\025searchingB" +
      "yPeriodImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_periodRequested_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_periodRequested_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_periodRequested_descriptor,
        new java.lang.String[] { "ConsultingPeriod", });
    internal_static_identifyPeriod_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_identifyPeriod_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identifyPeriod_descriptor,
        new java.lang.String[] { "ConsultingPeriod", "PeriodIdentification", });
    internal_static_resourseType_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_resourseType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resourseType_descriptor,
        new java.lang.String[] { "MyResourseType", });
    internal_static_registrationTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_registrationTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registrationTypeResponse_descriptor,
        new java.lang.String[] { "NaturalResourceRegistered", });
    internal_static_reportAirWaterQuality_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_reportAirWaterQuality_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reportAirWaterQuality_descriptor,
        new java.lang.String[] { "ConsultingPeriod", "MyResourseType", "QualityReport", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
