// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userCollaboration.proto

package grpc.newServices;

public final class userCollaborationImpl {
  private userCollaborationImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_enterCity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_enterCity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_displayLocationDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_displayLocationDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_addInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_addInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_responseAddInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_responseAddInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_selectViewInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_selectViewInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_responseDataRecorded_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_responseDataRecorded_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027userCollaboration.proto\"\036\n\tenterCity\022\021" +
      "\n\tcityAdded\030\003 \001(\t\"h\n\026displayLocationDeta" +
      "ils\022\021\n\tcityAdded\030\003 \001(\t\022\035\n\025confirmingCity" +
      "Details\030\002 \001(\t\022\034\n\024locationConfirmation\030\001 " +
      "\001(\010\"&\n\007addInfo\022\033\n\023naturalResourceInfo\030\004 " +
      "\001(\t\"o\n\017responseAddInfo\022\033\n\023naturalResourc" +
      "eInfo\030\004 \001(\t\022\035\n\025resourcesConfirmation\030\001 \001" +
      "(\010\022 \n\030naturalResourceLastAdded\030\005 \001(\t\",\n\016" +
      "selectViewInfo\022\032\n\022viewInfoRegistered\030\001 \001" +
      "(\t\"t\n\024responseDataRecorded\022\033\n\023displayDat" +
      "aRecorded\030\001 \001(\t\022\035\n\025confirmingCityDetails" +
      "\030\002 \001(\t\022 \n\030naturalResourceLastAdded\030\005 \001(\t" +
      "2\277\001\n\021userCollaboration\0228\n\renterLocation\022" +
      "\n.enterCity\032\027.displayLocationDetails\"\0000\001" +
      "\0221\n\raddingDetails\022\010.addInfo\032\020.responseAd" +
      "dInfo\"\000(\0010\001\022=\n\017displayRecorded\022\017.selectV" +
      "iewInfo\032\025.responseDataRecorded\"\0000\001B+\n\020gr" +
      "pc.newServicesB\025userCollaborationImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_enterCity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_enterCity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_enterCity_descriptor,
        new java.lang.String[] { "CityAdded", });
    internal_static_displayLocationDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_displayLocationDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_displayLocationDetails_descriptor,
        new java.lang.String[] { "CityAdded", "ConfirmingCityDetails", "LocationConfirmation", });
    internal_static_addInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_addInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_addInfo_descriptor,
        new java.lang.String[] { "NaturalResourceInfo", });
    internal_static_responseAddInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_responseAddInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_responseAddInfo_descriptor,
        new java.lang.String[] { "NaturalResourceInfo", "ResourcesConfirmation", "NaturalResourceLastAdded", });
    internal_static_selectViewInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_selectViewInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_selectViewInfo_descriptor,
        new java.lang.String[] { "ViewInfoRegistered", });
    internal_static_responseDataRecorded_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_responseDataRecorded_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_responseDataRecorded_descriptor,
        new java.lang.String[] { "DisplayDataRecorded", "ConfirmingCityDetails", "NaturalResourceLastAdded", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
