// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.Service2;

public interface identifyPeriodOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identifyPeriod)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *It will be start date until end date
   * </pre>
   *
   * <code>string periodMsg = 1;</code>
   */
  java.lang.String getPeriodMsg();
  /**
   * <pre>
   *It will be start date until end date
   * </pre>
   *
   * <code>string periodMsg = 1;</code>
   */
  com.google.protobuf.ByteString
      getPeriodMsgBytes();
}
