// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.Service2;

public interface periodRequestedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:periodRequested)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string startDate = 1;</code>
   */
  java.lang.String getStartDate();
  /**
   * <code>string startDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string endDate = 2;</code>
   */
  java.lang.String getEndDate();
  /**
   * <code>string endDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getEndDateBytes();
}
