// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.Service2;

/**
 * Protobuf type {@code registrationTypeResponse}
 */
public  final class registrationTypeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:registrationTypeResponse)
    registrationTypeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use registrationTypeResponse.newBuilder() to construct.
  private registrationTypeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private registrationTypeResponse() {
    naturalResourceRegistered_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private registrationTypeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            naturalResourceRegistered_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.Service2.Service2Impl.internal_static_registrationTypeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.Service2.Service2Impl.internal_static_registrationTypeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.Service2.registrationTypeResponse.class, ds.Service2.registrationTypeResponse.Builder.class);
  }

  public static final int NATURALRESOURCEREGISTERED_FIELD_NUMBER = 2;
  private volatile java.lang.Object naturalResourceRegistered_;
  /**
   * <pre>
   *ver se é para estã na posição 1
   * </pre>
   *
   * <code>string naturalResourceRegistered = 2;</code>
   */
  public java.lang.String getNaturalResourceRegistered() {
    java.lang.Object ref = naturalResourceRegistered_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      naturalResourceRegistered_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *ver se é para estã na posição 1
   * </pre>
   *
   * <code>string naturalResourceRegistered = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNaturalResourceRegisteredBytes() {
    java.lang.Object ref = naturalResourceRegistered_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      naturalResourceRegistered_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNaturalResourceRegisteredBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, naturalResourceRegistered_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNaturalResourceRegisteredBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, naturalResourceRegistered_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.Service2.registrationTypeResponse)) {
      return super.equals(obj);
    }
    ds.Service2.registrationTypeResponse other = (ds.Service2.registrationTypeResponse) obj;

    boolean result = true;
    result = result && getNaturalResourceRegistered()
        .equals(other.getNaturalResourceRegistered());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NATURALRESOURCEREGISTERED_FIELD_NUMBER;
    hash = (53 * hash) + getNaturalResourceRegistered().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.Service2.registrationTypeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service2.registrationTypeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service2.registrationTypeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service2.registrationTypeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service2.registrationTypeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service2.registrationTypeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service2.registrationTypeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.Service2.registrationTypeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.Service2.registrationTypeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.Service2.registrationTypeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.Service2.registrationTypeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.Service2.registrationTypeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.Service2.registrationTypeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code registrationTypeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:registrationTypeResponse)
      ds.Service2.registrationTypeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.Service2.Service2Impl.internal_static_registrationTypeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.Service2.Service2Impl.internal_static_registrationTypeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.Service2.registrationTypeResponse.class, ds.Service2.registrationTypeResponse.Builder.class);
    }

    // Construct using ds.Service2.registrationTypeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      naturalResourceRegistered_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.Service2.Service2Impl.internal_static_registrationTypeResponse_descriptor;
    }

    @java.lang.Override
    public ds.Service2.registrationTypeResponse getDefaultInstanceForType() {
      return ds.Service2.registrationTypeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.Service2.registrationTypeResponse build() {
      ds.Service2.registrationTypeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.Service2.registrationTypeResponse buildPartial() {
      ds.Service2.registrationTypeResponse result = new ds.Service2.registrationTypeResponse(this);
      result.naturalResourceRegistered_ = naturalResourceRegistered_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.Service2.registrationTypeResponse) {
        return mergeFrom((ds.Service2.registrationTypeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.Service2.registrationTypeResponse other) {
      if (other == ds.Service2.registrationTypeResponse.getDefaultInstance()) return this;
      if (!other.getNaturalResourceRegistered().isEmpty()) {
        naturalResourceRegistered_ = other.naturalResourceRegistered_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.Service2.registrationTypeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.Service2.registrationTypeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object naturalResourceRegistered_ = "";
    /**
     * <pre>
     *ver se é para estã na posição 1
     * </pre>
     *
     * <code>string naturalResourceRegistered = 2;</code>
     */
    public java.lang.String getNaturalResourceRegistered() {
      java.lang.Object ref = naturalResourceRegistered_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        naturalResourceRegistered_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *ver se é para estã na posição 1
     * </pre>
     *
     * <code>string naturalResourceRegistered = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNaturalResourceRegisteredBytes() {
      java.lang.Object ref = naturalResourceRegistered_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        naturalResourceRegistered_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *ver se é para estã na posição 1
     * </pre>
     *
     * <code>string naturalResourceRegistered = 2;</code>
     */
    public Builder setNaturalResourceRegistered(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      naturalResourceRegistered_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *ver se é para estã na posição 1
     * </pre>
     *
     * <code>string naturalResourceRegistered = 2;</code>
     */
    public Builder clearNaturalResourceRegistered() {
      
      naturalResourceRegistered_ = getDefaultInstance().getNaturalResourceRegistered();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *ver se é para estã na posição 1
     * </pre>
     *
     * <code>string naturalResourceRegistered = 2;</code>
     */
    public Builder setNaturalResourceRegisteredBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      naturalResourceRegistered_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:registrationTypeResponse)
  }

  // @@protoc_insertion_point(class_scope:registrationTypeResponse)
  private static final ds.Service2.registrationTypeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.Service2.registrationTypeResponse();
  }

  public static ds.Service2.registrationTypeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<registrationTypeResponse>
      PARSER = new com.google.protobuf.AbstractParser<registrationTypeResponse>() {
    @java.lang.Override
    public registrationTypeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new registrationTypeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<registrationTypeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<registrationTypeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.Service2.registrationTypeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

