// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.Service2;

/**
 * Protobuf type {@code reportAirWaterQuality}
 */
public  final class reportAirWaterQuality extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:reportAirWaterQuality)
    reportAirWaterQualityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use reportAirWaterQuality.newBuilder() to construct.
  private reportAirWaterQuality(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private reportAirWaterQuality() {
    periodMsg_ = "";
    myResourseType_ = "";
    qualityReport_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private reportAirWaterQuality(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            periodMsg_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            myResourseType_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            qualityReport_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.Service2.Service2Impl.internal_static_reportAirWaterQuality_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.Service2.Service2Impl.internal_static_reportAirWaterQuality_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.Service2.reportAirWaterQuality.class, ds.Service2.reportAirWaterQuality.Builder.class);
  }

  public static final int PERIODMSG_FIELD_NUMBER = 1;
  private volatile java.lang.Object periodMsg_;
  /**
   * <code>string periodMsg = 1;</code>
   */
  public java.lang.String getPeriodMsg() {
    java.lang.Object ref = periodMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      periodMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string periodMsg = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPeriodMsgBytes() {
    java.lang.Object ref = periodMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      periodMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MYRESOURSETYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object myResourseType_;
  /**
   * <code>string myResourseType = 2;</code>
   */
  public java.lang.String getMyResourseType() {
    java.lang.Object ref = myResourseType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      myResourseType_ = s;
      return s;
    }
  }
  /**
   * <code>string myResourseType = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMyResourseTypeBytes() {
    java.lang.Object ref = myResourseType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      myResourseType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUALITYREPORT_FIELD_NUMBER = 3;
  private volatile java.lang.Object qualityReport_;
  /**
   * <code>string qualityReport = 3;</code>
   */
  public java.lang.String getQualityReport() {
    java.lang.Object ref = qualityReport_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      qualityReport_ = s;
      return s;
    }
  }
  /**
   * <code>string qualityReport = 3;</code>
   */
  public com.google.protobuf.ByteString
      getQualityReportBytes() {
    java.lang.Object ref = qualityReport_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      qualityReport_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPeriodMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, periodMsg_);
    }
    if (!getMyResourseTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, myResourseType_);
    }
    if (!getQualityReportBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, qualityReport_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPeriodMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, periodMsg_);
    }
    if (!getMyResourseTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, myResourseType_);
    }
    if (!getQualityReportBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, qualityReport_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.Service2.reportAirWaterQuality)) {
      return super.equals(obj);
    }
    ds.Service2.reportAirWaterQuality other = (ds.Service2.reportAirWaterQuality) obj;

    boolean result = true;
    result = result && getPeriodMsg()
        .equals(other.getPeriodMsg());
    result = result && getMyResourseType()
        .equals(other.getMyResourseType());
    result = result && getQualityReport()
        .equals(other.getQualityReport());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PERIODMSG_FIELD_NUMBER;
    hash = (53 * hash) + getPeriodMsg().hashCode();
    hash = (37 * hash) + MYRESOURSETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMyResourseType().hashCode();
    hash = (37 * hash) + QUALITYREPORT_FIELD_NUMBER;
    hash = (53 * hash) + getQualityReport().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.Service2.reportAirWaterQuality parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service2.reportAirWaterQuality parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service2.reportAirWaterQuality parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service2.reportAirWaterQuality parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service2.reportAirWaterQuality parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.Service2.reportAirWaterQuality parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.Service2.reportAirWaterQuality parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.Service2.reportAirWaterQuality parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.Service2.reportAirWaterQuality parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.Service2.reportAirWaterQuality parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.Service2.reportAirWaterQuality parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.Service2.reportAirWaterQuality parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.Service2.reportAirWaterQuality prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reportAirWaterQuality}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reportAirWaterQuality)
      ds.Service2.reportAirWaterQualityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.Service2.Service2Impl.internal_static_reportAirWaterQuality_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.Service2.Service2Impl.internal_static_reportAirWaterQuality_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.Service2.reportAirWaterQuality.class, ds.Service2.reportAirWaterQuality.Builder.class);
    }

    // Construct using ds.Service2.reportAirWaterQuality.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      periodMsg_ = "";

      myResourseType_ = "";

      qualityReport_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.Service2.Service2Impl.internal_static_reportAirWaterQuality_descriptor;
    }

    @java.lang.Override
    public ds.Service2.reportAirWaterQuality getDefaultInstanceForType() {
      return ds.Service2.reportAirWaterQuality.getDefaultInstance();
    }

    @java.lang.Override
    public ds.Service2.reportAirWaterQuality build() {
      ds.Service2.reportAirWaterQuality result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.Service2.reportAirWaterQuality buildPartial() {
      ds.Service2.reportAirWaterQuality result = new ds.Service2.reportAirWaterQuality(this);
      result.periodMsg_ = periodMsg_;
      result.myResourseType_ = myResourseType_;
      result.qualityReport_ = qualityReport_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.Service2.reportAirWaterQuality) {
        return mergeFrom((ds.Service2.reportAirWaterQuality)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.Service2.reportAirWaterQuality other) {
      if (other == ds.Service2.reportAirWaterQuality.getDefaultInstance()) return this;
      if (!other.getPeriodMsg().isEmpty()) {
        periodMsg_ = other.periodMsg_;
        onChanged();
      }
      if (!other.getMyResourseType().isEmpty()) {
        myResourseType_ = other.myResourseType_;
        onChanged();
      }
      if (!other.getQualityReport().isEmpty()) {
        qualityReport_ = other.qualityReport_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.Service2.reportAirWaterQuality parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.Service2.reportAirWaterQuality) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object periodMsg_ = "";
    /**
     * <code>string periodMsg = 1;</code>
     */
    public java.lang.String getPeriodMsg() {
      java.lang.Object ref = periodMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        periodMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string periodMsg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPeriodMsgBytes() {
      java.lang.Object ref = periodMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        periodMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string periodMsg = 1;</code>
     */
    public Builder setPeriodMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      periodMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string periodMsg = 1;</code>
     */
    public Builder clearPeriodMsg() {
      
      periodMsg_ = getDefaultInstance().getPeriodMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string periodMsg = 1;</code>
     */
    public Builder setPeriodMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      periodMsg_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object myResourseType_ = "";
    /**
     * <code>string myResourseType = 2;</code>
     */
    public java.lang.String getMyResourseType() {
      java.lang.Object ref = myResourseType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        myResourseType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string myResourseType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMyResourseTypeBytes() {
      java.lang.Object ref = myResourseType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        myResourseType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string myResourseType = 2;</code>
     */
    public Builder setMyResourseType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      myResourseType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string myResourseType = 2;</code>
     */
    public Builder clearMyResourseType() {
      
      myResourseType_ = getDefaultInstance().getMyResourseType();
      onChanged();
      return this;
    }
    /**
     * <code>string myResourseType = 2;</code>
     */
    public Builder setMyResourseTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      myResourseType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object qualityReport_ = "";
    /**
     * <code>string qualityReport = 3;</code>
     */
    public java.lang.String getQualityReport() {
      java.lang.Object ref = qualityReport_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        qualityReport_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string qualityReport = 3;</code>
     */
    public com.google.protobuf.ByteString
        getQualityReportBytes() {
      java.lang.Object ref = qualityReport_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        qualityReport_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string qualityReport = 3;</code>
     */
    public Builder setQualityReport(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      qualityReport_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string qualityReport = 3;</code>
     */
    public Builder clearQualityReport() {
      
      qualityReport_ = getDefaultInstance().getQualityReport();
      onChanged();
      return this;
    }
    /**
     * <code>string qualityReport = 3;</code>
     */
    public Builder setQualityReportBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      qualityReport_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:reportAirWaterQuality)
  }

  // @@protoc_insertion_point(class_scope:reportAirWaterQuality)
  private static final ds.Service2.reportAirWaterQuality DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.Service2.reportAirWaterQuality();
  }

  public static ds.Service2.reportAirWaterQuality getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<reportAirWaterQuality>
      PARSER = new com.google.protobuf.AbstractParser<reportAirWaterQuality>() {
    @java.lang.Override
    public reportAirWaterQuality parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new reportAirWaterQuality(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<reportAirWaterQuality> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<reportAirWaterQuality> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.Service2.reportAirWaterQuality getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

