// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.Service2;

public interface reportAirWaterQualityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reportAirWaterQuality)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string periodMsg = 1;</code>
   */
  java.lang.String getPeriodMsg();
  /**
   * <code>string periodMsg = 1;</code>
   */
  com.google.protobuf.ByteString
      getPeriodMsgBytes();

  /**
   * <code>string myResourseType = 2;</code>
   */
  java.lang.String getMyResourseType();
  /**
   * <code>string myResourseType = 2;</code>
   */
  com.google.protobuf.ByteString
      getMyResourseTypeBytes();

  /**
   * <code>string qualityReport = 3;</code>
   */
  java.lang.String getQualityReport();
  /**
   * <code>string qualityReport = 3;</code>
   */
  com.google.protobuf.ByteString
      getQualityReportBytes();
}
