// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.Service2;

public interface resourceTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resourceType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string myResourceType = 1;</code>
   */
  java.lang.String getMyResourceType();
  /**
   * <code>string myResourceType = 1;</code>
   */
  com.google.protobuf.ByteString
      getMyResourceTypeBytes();
}
