// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.Service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_periodRequested_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_periodRequested_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identifyPeriod_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identifyPeriod_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resourseType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resourseType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registrationTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registrationTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reportAirWaterQuality_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reportAirWaterQuality_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\"5\n\017periodRequested\022\021\n\ts" +
      "tartDate\030\001 \001(\t\022\017\n\007endDate\030\002 \001(\t\"#\n\016ident" +
      "ifyPeriod\022\021\n\tperiodMsg\030\001 \001(\t\"&\n\014resourse" +
      "Type\022\026\n\016myResourseType\030\001 \001(\t\"=\n\030registra" +
      "tionTypeResponse\022!\n\031naturalResourceRegis" +
      "tered\030\002 \001(\t\"Y\n\025reportAirWaterQuality\022\021\n\t" +
      "periodMsg\030\001 \001(\t\022\026\n\016myResourseType\030\002 \001(\t\022" +
      "\025\n\rqualityReport\030\003 \001(\t2\323\001\n\010service2\0226\n\rr" +
      "equestPeriod\022\020.periodRequested\032\017.identif" +
      "yPeriod\"\000(\001\022F\n\030enterNaturalResourcetype\022" +
      "\r.resourseType\032\031.registrationTypeRespons" +
      "e\"\000\022G\n\030returnAirQualitybyPeriod\022\017.identi" +
      "fyPeriod\032\026.reportAirWaterQuality\"\0000\001B\035\n\013" +
      "ds.Service2B\014Service2ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_periodRequested_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_periodRequested_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_periodRequested_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", });
    internal_static_identifyPeriod_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_identifyPeriod_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identifyPeriod_descriptor,
        new java.lang.String[] { "PeriodMsg", });
    internal_static_resourseType_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_resourseType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resourseType_descriptor,
        new java.lang.String[] { "MyResourseType", });
    internal_static_registrationTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_registrationTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registrationTypeResponse_descriptor,
        new java.lang.String[] { "NaturalResourceRegistered", });
    internal_static_reportAirWaterQuality_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_reportAirWaterQuality_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reportAirWaterQuality_descriptor,
        new java.lang.String[] { "PeriodMsg", "MyResourseType", "QualityReport", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
