// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.Service1;

public interface displayCityInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:displayCityInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataCityInfo = 1;</code>
   */
  java.lang.String getDataCityInfo();
  /**
   * <code>string dataCityInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataCityInfoBytes();

  /**
   * <code>bool emptyCityInput = 2;</code>
   */
  boolean getEmptyCityInput();

  /**
   * <code>string errorMessage = 3;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
