// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.Service1;

public interface enterLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:enterLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataCityInfo = 1;</code>
   */
  java.lang.String getDataCityInfo();
  /**
   * <code>string dataCityInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataCityInfoBytes();
}
