// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.Service1;

public interface waterAirQualityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterAirQuality)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataCityInfo = 1;</code>
   */
  java.lang.String getDataCityInfo();
  /**
   * <code>string dataCityInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataCityInfoBytes();

  /**
   * <code>string stationFound = 2;</code>
   */
  java.lang.String getStationFound();
  /**
   * <code>string stationFound = 2;</code>
   */
  com.google.protobuf.ByteString
      getStationFoundBytes();

  /**
   * <code>string reportAirQuality = 3;</code>
   */
  java.lang.String getReportAirQuality();
  /**
   * <code>string reportAirQuality = 3;</code>
   */
  com.google.protobuf.ByteString
      getReportAirQualityBytes();
}
