// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userCollaboration.proto

package ds.UserCollaboration;

/**
 * Protobuf type {@code responseAddInfo}
 */
public  final class responseAddInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:responseAddInfo)
    responseAddInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use responseAddInfo.newBuilder() to construct.
  private responseAddInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private responseAddInfo() {
    naturalResourceInfo_ = "";
    resourcesConfirmation_ = false;
    naturalResourceLastAdded_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private responseAddInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            resourcesConfirmation_ = input.readBool();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            naturalResourceInfo_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            naturalResourceLastAdded_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.UserCollaboration.userCollaborationImpl.internal_static_responseAddInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.UserCollaboration.userCollaborationImpl.internal_static_responseAddInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.UserCollaboration.responseAddInfo.class, ds.UserCollaboration.responseAddInfo.Builder.class);
  }

  public static final int NATURALRESOURCEINFO_FIELD_NUMBER = 4;
  private volatile java.lang.Object naturalResourceInfo_;
  /**
   * <code>string naturalResourceInfo = 4;</code>
   */
  public java.lang.String getNaturalResourceInfo() {
    java.lang.Object ref = naturalResourceInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      naturalResourceInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string naturalResourceInfo = 4;</code>
   */
  public com.google.protobuf.ByteString
      getNaturalResourceInfoBytes() {
    java.lang.Object ref = naturalResourceInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      naturalResourceInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESOURCESCONFIRMATION_FIELD_NUMBER = 1;
  private boolean resourcesConfirmation_;
  /**
   * <code>bool resourcesConfirmation = 1;</code>
   */
  public boolean getResourcesConfirmation() {
    return resourcesConfirmation_;
  }

  public static final int NATURALRESOURCELASTADDED_FIELD_NUMBER = 5;
  private volatile java.lang.Object naturalResourceLastAdded_;
  /**
   * <code>string naturalResourceLastAdded = 5;</code>
   */
  public java.lang.String getNaturalResourceLastAdded() {
    java.lang.Object ref = naturalResourceLastAdded_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      naturalResourceLastAdded_ = s;
      return s;
    }
  }
  /**
   * <code>string naturalResourceLastAdded = 5;</code>
   */
  public com.google.protobuf.ByteString
      getNaturalResourceLastAddedBytes() {
    java.lang.Object ref = naturalResourceLastAdded_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      naturalResourceLastAdded_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resourcesConfirmation_ != false) {
      output.writeBool(1, resourcesConfirmation_);
    }
    if (!getNaturalResourceInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, naturalResourceInfo_);
    }
    if (!getNaturalResourceLastAddedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, naturalResourceLastAdded_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resourcesConfirmation_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, resourcesConfirmation_);
    }
    if (!getNaturalResourceInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, naturalResourceInfo_);
    }
    if (!getNaturalResourceLastAddedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, naturalResourceLastAdded_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.UserCollaboration.responseAddInfo)) {
      return super.equals(obj);
    }
    ds.UserCollaboration.responseAddInfo other = (ds.UserCollaboration.responseAddInfo) obj;

    boolean result = true;
    result = result && getNaturalResourceInfo()
        .equals(other.getNaturalResourceInfo());
    result = result && (getResourcesConfirmation()
        == other.getResourcesConfirmation());
    result = result && getNaturalResourceLastAdded()
        .equals(other.getNaturalResourceLastAdded());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NATURALRESOURCEINFO_FIELD_NUMBER;
    hash = (53 * hash) + getNaturalResourceInfo().hashCode();
    hash = (37 * hash) + RESOURCESCONFIRMATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getResourcesConfirmation());
    hash = (37 * hash) + NATURALRESOURCELASTADDED_FIELD_NUMBER;
    hash = (53 * hash) + getNaturalResourceLastAdded().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.UserCollaboration.responseAddInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.UserCollaboration.responseAddInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.UserCollaboration.responseAddInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.UserCollaboration.responseAddInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.UserCollaboration.responseAddInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.UserCollaboration.responseAddInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.UserCollaboration.responseAddInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.UserCollaboration.responseAddInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.UserCollaboration.responseAddInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.UserCollaboration.responseAddInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.UserCollaboration.responseAddInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.UserCollaboration.responseAddInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.UserCollaboration.responseAddInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code responseAddInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:responseAddInfo)
      ds.UserCollaboration.responseAddInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.UserCollaboration.userCollaborationImpl.internal_static_responseAddInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.UserCollaboration.userCollaborationImpl.internal_static_responseAddInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.UserCollaboration.responseAddInfo.class, ds.UserCollaboration.responseAddInfo.Builder.class);
    }

    // Construct using ds.UserCollaboration.responseAddInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      naturalResourceInfo_ = "";

      resourcesConfirmation_ = false;

      naturalResourceLastAdded_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.UserCollaboration.userCollaborationImpl.internal_static_responseAddInfo_descriptor;
    }

    @java.lang.Override
    public ds.UserCollaboration.responseAddInfo getDefaultInstanceForType() {
      return ds.UserCollaboration.responseAddInfo.getDefaultInstance();
    }

    @java.lang.Override
    public ds.UserCollaboration.responseAddInfo build() {
      ds.UserCollaboration.responseAddInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.UserCollaboration.responseAddInfo buildPartial() {
      ds.UserCollaboration.responseAddInfo result = new ds.UserCollaboration.responseAddInfo(this);
      result.naturalResourceInfo_ = naturalResourceInfo_;
      result.resourcesConfirmation_ = resourcesConfirmation_;
      result.naturalResourceLastAdded_ = naturalResourceLastAdded_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.UserCollaboration.responseAddInfo) {
        return mergeFrom((ds.UserCollaboration.responseAddInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.UserCollaboration.responseAddInfo other) {
      if (other == ds.UserCollaboration.responseAddInfo.getDefaultInstance()) return this;
      if (!other.getNaturalResourceInfo().isEmpty()) {
        naturalResourceInfo_ = other.naturalResourceInfo_;
        onChanged();
      }
      if (other.getResourcesConfirmation() != false) {
        setResourcesConfirmation(other.getResourcesConfirmation());
      }
      if (!other.getNaturalResourceLastAdded().isEmpty()) {
        naturalResourceLastAdded_ = other.naturalResourceLastAdded_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.UserCollaboration.responseAddInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.UserCollaboration.responseAddInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object naturalResourceInfo_ = "";
    /**
     * <code>string naturalResourceInfo = 4;</code>
     */
    public java.lang.String getNaturalResourceInfo() {
      java.lang.Object ref = naturalResourceInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        naturalResourceInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string naturalResourceInfo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNaturalResourceInfoBytes() {
      java.lang.Object ref = naturalResourceInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        naturalResourceInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string naturalResourceInfo = 4;</code>
     */
    public Builder setNaturalResourceInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      naturalResourceInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string naturalResourceInfo = 4;</code>
     */
    public Builder clearNaturalResourceInfo() {
      
      naturalResourceInfo_ = getDefaultInstance().getNaturalResourceInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string naturalResourceInfo = 4;</code>
     */
    public Builder setNaturalResourceInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      naturalResourceInfo_ = value;
      onChanged();
      return this;
    }

    private boolean resourcesConfirmation_ ;
    /**
     * <code>bool resourcesConfirmation = 1;</code>
     */
    public boolean getResourcesConfirmation() {
      return resourcesConfirmation_;
    }
    /**
     * <code>bool resourcesConfirmation = 1;</code>
     */
    public Builder setResourcesConfirmation(boolean value) {
      
      resourcesConfirmation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool resourcesConfirmation = 1;</code>
     */
    public Builder clearResourcesConfirmation() {
      
      resourcesConfirmation_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object naturalResourceLastAdded_ = "";
    /**
     * <code>string naturalResourceLastAdded = 5;</code>
     */
    public java.lang.String getNaturalResourceLastAdded() {
      java.lang.Object ref = naturalResourceLastAdded_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        naturalResourceLastAdded_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string naturalResourceLastAdded = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNaturalResourceLastAddedBytes() {
      java.lang.Object ref = naturalResourceLastAdded_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        naturalResourceLastAdded_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string naturalResourceLastAdded = 5;</code>
     */
    public Builder setNaturalResourceLastAdded(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      naturalResourceLastAdded_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string naturalResourceLastAdded = 5;</code>
     */
    public Builder clearNaturalResourceLastAdded() {
      
      naturalResourceLastAdded_ = getDefaultInstance().getNaturalResourceLastAdded();
      onChanged();
      return this;
    }
    /**
     * <code>string naturalResourceLastAdded = 5;</code>
     */
    public Builder setNaturalResourceLastAddedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      naturalResourceLastAdded_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:responseAddInfo)
  }

  // @@protoc_insertion_point(class_scope:responseAddInfo)
  private static final ds.UserCollaboration.responseAddInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.UserCollaboration.responseAddInfo();
  }

  public static ds.UserCollaboration.responseAddInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<responseAddInfo>
      PARSER = new com.google.protobuf.AbstractParser<responseAddInfo>() {
    @java.lang.Override
    public responseAddInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new responseAddInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<responseAddInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<responseAddInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.UserCollaboration.responseAddInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

