// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userCollaboration.proto

package ds.UserCollaboration;

public interface responseAddInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:responseAddInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string naturalResourceInfo = 4;</code>
   */
  java.lang.String getNaturalResourceInfo();
  /**
   * <code>string naturalResourceInfo = 4;</code>
   */
  com.google.protobuf.ByteString
      getNaturalResourceInfoBytes();

  /**
   * <code>bool resourcesConfirmation = 1;</code>
   */
  boolean getResourcesConfirmation();

  /**
   * <code>string naturalResourceLastAdded = 5;</code>
   */
  java.lang.String getNaturalResourceLastAdded();
  /**
   * <code>string naturalResourceLastAdded = 5;</code>
   */
  com.google.protobuf.ByteString
      getNaturalResourceLastAddedBytes();
}
